[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "SMART"
authors = [{name = "Qiyi Chen", email = "2210274047@email.szu.edu.cn"}]
dynamic = ["version", "description"]
